#Here is the configfile of BookShop:
#Read the comments please!
#This choose the language.
language: en
UsePrefix: true
Prefix: BookShop
PrefixColor: b
TextColor: 6
FirstLineOfEveryShop: '[BookShop]'
AdminShop: AdminShop
#This is the language config: edit these if you add an new language, or you want other sentences, but never delete parts beginning with "%"!
permissions:
  error:
    de: Wir haben ein Problem! Dies darfst Du nicht machen!
    en: we have a problem! You musnt do this!
Shop:
  success:
    create:
      de: Shop erfolgreich erstellt.
      en: Shop created successfully.
    buy:
      de: Du hast das Buch '%1$s' von %2$s fuer %3$s gekauft.
      en: You bought the book '%1$s' from %2$s for %3$s.
    sellerbuy:
      de: Player %2$s hat von Dir das Buch '%1$s' fuer %3$s gekauft.
      en: Player %2$s has bought the book '%1$s' from you for %3$s.
    books:
      de: Du kannst beschreibare Buecher in die Kiste legen um den Kaeufern das mitbringen von Buechern zu ersparen.
      en: You can place book and quill in the chest, so players neednt to take a book with them if they want to purchase a book.
  error:
    onlyyourbooks:
      de: Du darfst nur eigene Buecher verkaufen. Du hast die Permission BookShop.sell.other nicht!
      en: You are only allowed to sell your own books. You havent got the Permission BookShop.sell.other!
    inventoryfull:
      de: Dein Inventar ist voll! Bitte leere es um hier kaufen zu koennen.
      en: Your inventory is full! Please clear some slots to purchase here.
    basecost:
      de: Der Mindestpreis ist %1$s!
      en: The lowest price is %1$s!
    notenoughmoneyconsumer:
      de: Du hast nicht genug Geld!
      en: You havent got enough money!
    notyourshop:
      de: Du hast keinen Zugriff auf diesen Shop!
      en: You are NOT allowed to open this shop!
    nochest:
      de: Der Shop benoetigt eine leere Kiste unterhalb des Schildes!
      en: The shop needs a empty chest under the sign!
    nochest2:
      de: Der Shop benoetigt eine Kiste unterhalb des Schildes!
      en: The shop needs a chest under the sign!
    nobook:
      de: Kein Buch im Shop gefunden!
      en: No book found in the shop!
    onebook:
      de: Es darf nur EIN Buch im Shop sein!
      en: Only ONE book is allowed per shop!
    wrongPrice:
      de: Falscher Preis!
      en: Wrong price!
    wrongItem:
      de: Es duerfen nur fertige Buecher in die Kiste gelegt werden!
      en: You are only allowed to place finished books in the chest!
    takeBookandQuill:
      de: Bitte nimm ein Buch mit Feder in die Hand um ein Buch zu kaufen!
      en: Please take one Book and Quill in the hand to purchase a book!