name: BookShop
version: 6.0
description: Shop for books.
author: ibhh, Brokkonaut
softdepend: [Vault, PlayerUUIDCache]

main: me.ibhh.BookShop.BookShop

commands:
  BookShop:
    description: Version information
permissions:
  BookShop.admin:
    description: Gives you full access to bookshop.
    children:
      BookShop.use: true
      BookShop.create: true
      BookShop.sellother: true
    default: op
  BookShop.use:
    description: Allows you to buy books.
    default: true
  BookShop.create:
    description: Allows you to create bookshops.
    default: op
  BookShop.sellother:
    description: Allows you to sell books not written by you.
    default: op